services:
    laravel-test-1:
        image: image-laravel-test-1
        container_name: container-laravel-test-1
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ../:/var/www/laravel-test-1
        depends_on:
            - container-postgres-test-v1
            # - elasticsearch
        ports:
            - "8000:80"
        networks:
            - mynetwork

    container-postgres-test-v1:
        image: postgres:13
        container_name: container-postgres
        restart: always
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: postgres
            DB_PORT: 5432
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: admin1
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - mynetwork

    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
        networks:
            - mynetwork

    vite:
        image: node:20
        container_name: container-vite
        working_dir: /var/www/laravel-test-1
        volumes:
            - ../:/var/www/laravel-test-1
        ports:
            - "5173:5173"
        command: sh -c "npm install && npm run dev"
        networks:
            - mynetwork


    # elasticsearch:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:9.1.0
    #     container_name: elasticsearch
    #     environment:
    #         - discovery.type=single-node
    #         - xpack.security.enabled=false
    #     volumes:
    #         - esdata:/usr/share/elasticsearch/data
    #     ports:
    #         - "9200:9200"
    #     networks:
    #         - mynetwork 

    # redis:
    #     image: redis:7
    #     ports:
    #     - "6379:6379"
    #     command: ["redis-server", "--appendonly", "yes"]
    #     volumes:
    #     - redis-data:/data

networks:
    mynetwork:
        driver: bridge

volumes:
    postgres_data:
    esdata:
    # redis-data:
