server {
    listen 80;
    server_name _;
    root /var/www/laravel-test-1/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass container-laravel-test-1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    access_log /var/log/nginx/laravel-test-1_access.log;
    error_log /var/log/nginx/laravel-test-1_error.log;

    location ~ /\.ht {
        deny all;
    }
}